apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc3zookeeper50G
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
