kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: docker.io/bitnami/kafka:2.5.0-debian-10-r29
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
              value: 51.79.72.49
            - name: NFS_PATH
              value: /opt/bitnami/kubernetes/localvolumes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 51.79.72.49
            path: /opt/bitnami/kubernetes/localvolumes
