kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 16
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: vdo.ai.com/nfs
            - name: NFS_SERVER
              value: 51.79.79.65
            - name: NFS_PATH
              value: /opt/bitnami/kubernetes/localvolumes
      volumes:
        - name: nfs-client-root
          nfs:
           server: 51.79.79.65
           path: /opt/bitnami/kubernetes/localvolumes

